use_frameworks!

platform :ios, '8.0'

target 'OBZuJianB_Example' do
  pod 'OBZuJianB', :path => '../'

  target 'OBZuJianB_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
